version: '3.8'

services:
  app:
    image: supershop-management:latest
    build: .
    container_name: supershop-app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/mydb
    restart: always

  mongo:
    image: mongo:6.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Admin123
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: Admin123
    ports:
      - "3306:3306"

volumes:
  mongo_data:
